services:
  postgres:
    image: postgres:17
    container_name: edu-postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    command: ["python", "-m", "uvicorn", "edu.main:get_app", "--factory", "--host", "0.0.0.0"]
    ports:
      - "0.0.0.0:8000:8000"
    expose:
      - "8000"

volumes:
  postgresql-data: