"""added users-tiers relationship

Revision ID: 1090a41c14a5
Revises: ff518ee9ab7e
Create Date: 2025-09-12 11:11:43.612746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1090a41c14a5'
down_revision: Union[str, Sequence[str], None] = 'ff518ee9ab7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tier_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_users_tier_id_tiers'), 'users', 'tiers', ['tier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_tier_id_tiers'), 'users', type_='foreignkey')
    op.drop_column('users', 'tier_id')
    # ### end Alembic commands ###
